version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django_template
      POSTGRES_PASSWORD: django_template
      POSTGRES_DB: django_template_dev
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "9000:9000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data: